### ISSUE TITLE
This plugin rocks!

### ISSUE THREAD

**Issue by GavinRay97** [mrkuz/kradle#1]
Thanks for making it, currently using it in my Kotlin projects =)

**Comment by mrkuz** [comment]
Thanks! I'm glad you find this useful.

I released a new major version a few days ago. There is now the plugin 'net.bitsandbobs.kradle', which is intended to combine the old plugins ''net.bitsandbobs.kradle-app' and 'net.bitsandbobs.kradle-lib'. The new plugin uses a different configuration DSL.

If you are interested in migration, I created a pull request for one of your projects:
https://github.com/GavinRay97/GraphQLCalcite/pull/1

After checking your project, I also fixed kradle to work with Gradle toolchains :)

Happy New Year!

**Comment by GavinRay97** [comment]
Wow, that was really nice of you. Happy New Year to you, too!

If it's useful to you, there are some tools Jetbrains recently released you might also find helpful btw:

- Kover, code-coverage plugin that works better for Kotlin code (like `inline` functions) and automatically integrates with gradle's test tasks + JaCoCo. No setup required.
    - https://www.youtube.com/watch?v=jNu5LY9HIbw
    - https://github.com/Kotlin/kotlinx-kover
- Qodana, static analysis tool that runs as a Docker container
    - https://www.jetbrains.com/qodana/
    - https://www.jetbrains.com/help/qodana/qodana-gradle-plugin.html

If you think there's any value in them, might be worthwhile adding as an option to the DSL `test` and `codeAnalysis` blocks =D

Qodana is nice right now because it's early development so they are letting everyone use the IntelliJ Ultimate analyses as an EAP:

![image](https://user-images.githubusercontent.com/26604994/147856981-b461a073-104e-4584-ab41-5311118e53cf.png)

**Comment by mrkuz** [comment]
Thanks for pointing out! I'll have a look :)
