### ISSUE TITLE
Dynamic dependencies possible?

### ISSUE THREAD

**Issue by GavinRay97** [mrkuz/kradle#2]
I'm curious whether it's possible for the plugin to optionally include dependencies, depending on the enabled status of a feature

Possibly useful:
- https://melix.github.io/blog/2022/03/gradle-conditional-dependencies.html

**Comment by mrkuz** [comment]
Hi!

The plugin uses dynamic dependencies internally, but currently there is no way to add you own.

Can you provide a kradle-specific use case and/or a pseudo `build.gradle` how you would like to see this feature implemented?

**Comment by GavinRay97** [comment]
Ah, I just meant whether or not it knew to exclude IE `jmh` if the benchmarking feature was not enabled

It sounds like that may be the case -- if so, I can close this!

**Comment by mrkuz** [comment]
Yes, this is the case. The dependencies are only added if required (you can check with `gradle dependencies`).

Also, test and benchmark dependencies are in their own [dependency configurations](https://docs.gradle.org/current/userguide/declaring_dependencies.html#sec:what-are-dependency-configurations). This ensures they are not part of the runtime classpath or the uber jar.
